# Generated by Django 6.0.1 on 2026-02-06 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='Created',
            new_name='created',
        ),
    ]
